yarnPath: .yarn/releases/yarn-sources.js
packageExtensions:
  "@storybook/core@*":
    peerDependencies:
      "@babel/core": "*"
  "corejs-upgrade-webpack-plugin@*":
    dependencies:
      babel-runtime: ^6.26.0
